## Python Crash Course

In this tutorial we will cover some basic aspects of Python using IPython (Jupyter) notebooks. 

1. Syntax
2. Data types
3. Loops and control structures
4. numpy, scipy, math

### Import modules to use

In [63]:
import math
import numpy as np

### Syntax

In [64]:
2 + 2+2+15

21

In [65]:
x = 5
y = 2
x * y

10

In [66]:
x ** y

25

In [67]:
print('Hello, world!')

Hello, world!


In [68]:
a='Hello'
print(a)

Hello


In [69]:
print('%s raised to power of %s equals %s' % (x, y, x ** y))

5 raised to power of 2 equals 25


In [102]:
print(f'Значення зміних: x= {x} , y= {y}')

Значення зміних: x= 5 , y= 2


### Data types

#### Boolean

'True' and 'False' have special meaning in Python.

In [70]:
a = True
b = False

In [71]:
a == True

True

In [72]:
b == True

False

In [73]:
a or b

True

In [74]:
a and b

False

#### Numbers: integers and floats

Numbers are pretty straightforward, especially in Python 3.

In [75]:
1 + 2

3

In [76]:
1.0 + 2.0

3.0

In [77]:
1 / 2

0.5

In [78]:
1.0 / 2.0

0.5

In [79]:
type(1)

int

In [80]:
type(1/2)

float

#### Strings

The next four data types -- strings, lists, tuples, arrays -- are all sequences.

Strings are sequences of characters.

In [81]:
s = 'Hello, world'

In [82]:
type(s)

str

In [83]:
s[0:10]

'Hello, wor'

In [84]:
s + '!'

'Hello, world!'

In [85]:
print(s)

Hello, world


In [86]:
s = s + '!'

In [87]:
s

'Hello, world!'

#### Lists

Lists are _mutable_ sequences of anything.

In [88]:
l = [0, 1, 1, 2, 3, 5, 8]

In [89]:
m = [5, 2, 'a', 'xxx', True, [0, 1]]

In [90]:
l[0:3]

[0, 1, 1]

In [91]:
m[4]

True

In [92]:
m[4] = False

In [93]:
m[0:]

[5, 2, 'a', 'xxx', False, [0, 1]]

#### Tuples

Tuples are immutable sequences of anything (similar to lists except you can't change them).

In [94]:
n = (3, 5, 6)

In [95]:
n[0:]

(3, 5, 6)

In [96]:
n[0] = 2

TypeError: 'tuple' object does not support item assignment

#### Arrays (numpy)

In [133]:
mylist = [0, 2, 4]
np.array(mylist)

array([0, 2, 4])

In [104]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [105]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [106]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [107]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [108]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [109]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [110]:
np.random.rand()

0.9713432237346731

In [111]:
np.random.rand(5)

array([0.90609146, 0.08226842, 0.30073684, 0.11650234, 0.54498664])

#### Sets

Sets are unordered collections of unique objects.

In [112]:
s1 = {'a', 'b', 'c'}
s2 = {'a', 'd', 'e'}

In [113]:
s1 & s2

{'a'}

In [114]:
s1 | s2

{'a', 'b', 'c', 'd', 'e'}

In [115]:
s3 = set(l)
s4 = set(m[0:2])

In [116]:
s3 & s4

{2, 5}

In [117]:
s3 | s4

{0, 1, 2, 3, 5, 8}

In [118]:
s3 - s4

{0, 1, 3, 8}

#### Dictionaries

Dictionaries or 'dicts' are hash tables, where a key points to a value.

In [119]:
d = {'name': 'John Doe', 'age': 27, 'dob': '7/20/1989'}

In [120]:
d

{'age': 27, 'dob': '7/20/1989', 'name': 'John Doe'}

In [121]:
d['age']

27

In [122]:
d['zip'] = 92039

In [123]:
d

{'age': 27, 'dob': '7/20/1989', 'name': 'John Doe', 'zip': 92039}

### Loops and control structures

#### Boolean and comparison operations

In [124]:
x = 5
(x < 6) and (x > 4)

True

In [125]:
x != 4

True

In [126]:
5 in [3, 4, 5]

True

In [127]:
'ell' in 'Hello'

True

In [128]:
len('Hello') >= 5

True

#### if tests

In [129]:
if 'f' in 'abc':
    print('Learn your alphabet.')
    print('dfgdfgdfgdfg')
elif (2 + 2 == 5):
    print('Sometimes yes.')
else: 
    print('Nothing is true.')    

Nothing is true.


#### while loops

In [130]:
i = 0
while (i < 5):
    print(i)
    i=i+ 1
print('End')

0
1
2
3
4
End


In [131]:
i

5

#### for loops

In [132]:
for x in [0, 1, 2, 3, 4]:
    print(x**2)

0
1
4
9
16


### Determining your Python version

#### Method 1: sys

In [ ]:
import sys

In [ ]:
sys.version

#### Method 2: platform

In [ ]:
import platform

In [ ]:
platform.python_version()

In [ ]:
platform.version()

#### Method 3: version_information

In [ ]:
#!pip install version_information

In [ ]:
# first install: pip install version_information
%reload_ext version_information
%version_information math, numpy, sys, platform